import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as cyberElements from 'react-cyber-elements'
import ReactTooltip from 'react-tooltip';

export default function Home() {
  console.log('cyber', cyberElements)
  const CyberEls = new Array(89).fill(undefined).map((_, i) => {
    return cyberElements[`CyberEl${i + 1}`]
  })
  return (
    <div className={styles.container}>
      <ReactTooltip />
      <Head>
        <title>React Cyber Punk Elements</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">react-cyber-elements</a>
        </h1>
        <h2>
          You can change the color of the elements with just css. 
        </h2>
        <div className="subtitle">
        Simple usage: {`<CyberEl1 />`} to {`<CyberEl99 />`}
        </div>
        <div className="subtitle">
          Checkout the <a rel="noreferrer" href="https://github.com/thiswallz/react-cyber-elements" target="_blank">docs</a>  and <a href="https://codesandbox.io/s/zen-cartwright-tcjjmq?file=/src/App.js" target="_blank" rel="noreferrer">sandbox</a> for more info.
        </div>
        <cyberElements.CyberEl14
          id="cyberEl-Master"
          style={{
            width: '150%',
            height: '150%'
          }} />

        <div className="container-sections">
          <section className="light">
            {
              CyberEls.map((CyberEl, i) => {
                return <CyberEl
                  data-tip={`<CyberEl${i + 1} />`}
                  key={i}
                  style={{
                    width: '100px',
                    height: '100px'
                  }}
                  id={`cyberEl${i + 1}`} />
              })
            }
          </section>
          <section className="dark">
            {
              CyberEls.map((CyberEl, i) => {
                return <CyberEl
                  data-tip={`<CyberEl${i + 1} />`}
                  key={i}
                  style={{
                    width: '100px',
                    height: '100px'
                  }}
                  id={`cyberEl${i + 1}`} />
              })
            }
          </section>
          <section className="custom">
            {
              CyberEls.map((CyberEl, i) => {
                return <CyberEl
                  data-tip={`<CyberEl${i + 1} />`}
                  key={i}
                  style={{
                    width: '100px',
                    height: '100px'
                  }}
                  id={`cyberEl${i + 1}`} />
              })
            }
          </section>
          <section className="custom-2">
            {
              CyberEls.map((CyberEl, i) => {
                return <CyberEl
                  data-tip={`<CyberEl${i + 1} />`}
                  key={i}
                  style={{
                    width: '100px',
                    height: '100px'
                  }}
                  id={`cyberEl${i + 1}`} />
              })
            }
          </section>
          <section className="custom-3">
            {
              CyberEls.map((CyberEl, i) => {
                return <CyberEl
                  data-tip={`<CyberEl${i + 1} />`}
                  key={i}
                  style={{
                    width: '100px',
                    height: '100px'
                  }}
                  id={`cyberEl${i + 1}`} />
              })
            }
          </section>

        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
